version: latest
services:

  mysql:
    image: mysql:9.1.0
    container_name: mysql-shopping-center
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shoppingCenter
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    container_name: shopping-center
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mysql-shopping-center
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=123456
      - DB_DATABASE=shoppingCenter

volumes:
  mysql_data:
