version: lates
services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql-shopping-center
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shoppingCenter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
