spring:
  application:
    name: shoppingCenter
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:shoppingCenter}
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: "81cffb936f7da3dd8b7a66a825b5d51c8f58b5e63664cbcc8710d09d7f5a7550"
  expiration: 86400000
